# Generated by Django 4.2.11 on 2026-04-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_classsession_monitoring_resumption_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='principal_docs/')),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_ingested', models.BooleanField(default=False)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.principal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
